### ISSUE TITLE
Fix urnik link

### ISSUE THREAD

**Issue by AuraDvin** [dondola-inc/jink.ml#2]
Link nekako odpre urnik za E1A, sej ni velik problem ampak je annoying

lp aura
![image](https://user-images.githubusercontent.com/87951242/164788322-5b75fb15-c812-44ba-9430-5d1f9a052d84.png)

novi link bi [torej bil](https://www.easistent.com/urniki/30a1b45414856e5598f2d137a5965d5a4ad36826/razredi/460308)

**Comment by Spacey4K** [comment]
Namenoma je blo *classless*
